### ISSUE TITLE
PEP8 Coding style

### ISSUE THREAD

**Issue by CHrlS98** [linum-uqam/linumpy#18]
We should try to follow the PEP8 coding standards, outlined here: https://peps.python.org/pep-0008/.

Some important points are:
* Limit line length to 79 characters
* Module names in lower case
* Class names in `CamelCase`
* Methods and variables in `snake_case`

We could add a [pep8speak bot](https://github.com/pep8speaks-org/pep8speaks) to the repo to validate compliance to pep8 standard in future pull requests.

(I'll make issues in the private repo but they might be related to the public one depending on whether we migrate stuff from the private to the public repo or just make the private repo public).

**Comment by joe-from-mtl** [comment]
That's a good idea. In the old gitlab repo, we had tools to check the style and that reformatted the files when the format changes didn't cause problems.  We could setup something similar for this repo

**Comment by joe-from-mtl** [comment]
I added the pep8speaklot bot
